# Generated by Django 5.0.6 on 2024-06-19 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevo',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevo',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='anos_de_experiencia',
            field=models.IntegerField(verbose_name='Años de experiencia'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_ejecucion',
            field=models.IntegerField(verbose_name='Fecha de ejecución'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socio',
            name='empresa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
