# Generated by Django 5.0.6 on 2024-06-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_cliente_empresa_alter_cliente_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos'),
        ),
    ]
